import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { Readable } from 'node:stream';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { createProjectStore } from '../project-store.mjs';
import { createStudioGateway } from '../studio-gateway.mjs';
import { createHypitScenes } from '../hypit-scenes.mjs';
import { createHypitProductions } from '../hypit-productions.mjs';
import { initializeProject } from '../starter.mjs';

import { fixture } from './author-fixture.mjs';

test('real Hypit author files check, plan, build and become editable candidates without another model session', { skip: !process.env.BEEFTV_HYPIT_ROOT }, async t => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), 'beeftv-production-'));
  const store = createProjectStore(root);
  const edit = await store.ensure('production_test');
  await initializeProject(store.workDir(edit.editId));
  const gateway = createStudioGateway(store);
  const scenes = createHypitScenes(store, gateway);
  const productions = createHypitProductions(store, scenes);
  t.after(async () => { await productions.close(); await gateway.close(); await fs.rm(root, { recursive: true, force: true }); });
  await productions.open(edit.editId);
  const skill = await productions.read(edit.editId, { area: 'skill', file: 'SKILL.md' });
  assert.match(skill.content, /name: hypit/);
  const { stdout: image } = await promisify(execFile)('ffmpeg', ['-v', 'error', '-f', 'lavfi', '-i', 'color=c=blue:s=64x96', '-frames:v', '1', '-f', 'image2pipe', '-vcodec', 'png', 'pipe:1'], { encoding: 'buffer', windowsHide: true });
  const metadata = { assetId: 'product', resourceId: 'saved-product', kind: 'image', mimeType: 'image/png', width: 64, height: 96, size: image.length, operationId: 'product_input', expectedRevision: 0 };
  const imported = await productions.importAsset(edit.editId, metadata, Readable.from(image));
  assert.equal((await productions.importAsset(edit.editId, metadata, Readable.from(image))).replayed, true);
  assert.equal((await productions.open(edit.editId)).inputs.length, 1);
  const reference = await productions.frames(edit.editId, { inputId: imported.inputId });
  assert.equal(reference.frames[0].mimeType, 'image/jpeg');
  assert.ok(Buffer.from(reference.frames[0].data, 'base64').length > 100);
  for (const [file, text] of Object.entries(fixture)) await productions.write(edit.editId, { file, text: text.replace('__INPUT__', './' + imported.file), expectedHash: null, operationId: `source_${Object.keys(fixture).indexOf(file)}` });
  await assert.rejects(productions.write(edit.editId, { file: 'main.svml', text: 'overwrite', expectedHash: null, operationId: 'stale' }), { reason: 'source_conflict' });
  await assert.rejects(productions.write(edit.editId, { file: '../outside.mjs', text: '', expectedHash: null, operationId: 'escape' }), { reason: 'unsafe_path' });
  await assert.rejects(productions.write(edit.editId, { file: 'hypit.runtime.json', text: '{}', expectedHash: null, operationId: 'provider' }), { reason: 'invalid_source' });
  async function finish(command) {
    const job = await productions.start(edit.editId, { command, source: 'main.svrun', operationId: command, expectedRevision: 0 });
    assert.equal((await productions.start(edit.editId, { command, source: 'main.svrun', operationId: command, expectedRevision: 0 })).jobId, job.jobId);
    const deadline = Date.now() + 90_000;
    let state;
    do { await new Promise(resolve => setTimeout(resolve, 100)); state = await productions.status(edit.editId, job.jobId); } while (state.status === 'running' && Date.now() < deadline);
    assert.equal(state.status, 'complete', JSON.stringify(state));
    return state;
  }
  await finish('check'); await finish('plan');
  const built = await finish('build');
  const candidate = await productions.publish(edit.editId, { jobId: built.jobId });
  assert.equal((await productions.publish(edit.editId, { jobId: built.jobId })).candidateId, candidate.candidateId);
  assert.equal(candidate.duration, 3);
  assert.ok(candidate.files.some(file => file.path.startsWith('assets/')), 'Real Build Result materializes the imported image');
  assert.equal((await store.state(edit.editId)).revision, 0, 'Production cannot overwrite the editable timeline');
  await scenes.promote(edit.editId, { candidateId: candidate.candidateId, operationId: 'publish' });
  const source = await fs.readFile(path.join(store.workDir(edit.editId), `scenes/${candidate.sceneId}/scene.html`), 'utf8');
  assert.match(source, /marker/);
  assert.equal((await productions.list(edit.editId)).length, 3);
  const cancelled = await productions.start(edit.editId, { command: 'build', source: 'main.svrun', operationId: 'cancel_build', expectedRevision: 1 });
  await productions.cancel(edit.editId, cancelled.jobId);
  let stopped;
  const cancellationDeadline = Date.now() + 45_000;
  do { await new Promise(resolve => setTimeout(resolve, 100)); stopped = await productions.status(edit.editId, cancelled.jobId); } while (stopped.status === 'running' && Date.now() < cancellationDeadline);
  assert.equal(stopped.status, 'cancelled', JSON.stringify(stopped));
  await assert.rejects(productions.publish(edit.editId, { jobId: cancelled.jobId }), { reason: 'production_not_ready' });
  const bundlePath = path.join(store.editDir(edit.editId), 'hypit/jobs', built.jobId, 'bundle.json');
  await fs.appendFile(bundlePath, ' ');
  await assert.rejects(productions.publish(edit.editId, { jobId: built.jobId }), { reason: 'production_changed' });
});
